package com.vegalife.filter;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.io.InputStream;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 * Cosine-similarity relevance scorer against two committed centroids (on-topic vs off-topic). Score
 * = (cos(text, onTopic) - cos(text, offTopic) + 1) / 2, clamped to [0, 1]; the band comes from the
 * {@code app.filter.accept-threshold} / {@code app.filter.reject-threshold} values (FR-006,
 * FR-007). The centroids are precomputed from the bilingual seed corpora in {@code
 * src/main/resources/filter/seed-*.txt} and regenerated by {@code CentroidRegenerationTest} when
 * {@code HF_TOKEN} is available.
 */
@Component
public class EmbeddingRelevanceScorer implements RelevanceScorer {

  public static final String CENTROIDS_RESOURCE = "/filter/centroids.json";

  private final float[] onTopic;
  private final float[] offTopic;
  private final double acceptThreshold;
  private final double rejectThreshold;

  /**
   * Spring wiring: loads the committed centroids and binds thresholds from {@code app.filter}.
   * Explicitly annotated because the public vector constructor below exists for tests.
   */
  @Autowired
  public EmbeddingRelevanceScorer(FilterProperties properties) {
    Centroids centroids = loadCentroids();
    validate(
        centroids.onTopic(),
        centroids.offTopic(),
        properties.getAcceptThreshold(),
        properties.getRejectThreshold());
    this.onTopic = centroids.onTopic();
    this.offTopic = centroids.offTopic();
    this.acceptThreshold = properties.getAcceptThreshold();
    this.rejectThreshold = properties.getRejectThreshold();
  }

  /**
   * Direct construction with explicit centroids and thresholds (used by unit tests).
   *
   * @param onTopic on-topic centroid vector
   * @param offTopic off-topic centroid vector, same length as {@code onTopic}
   * @param acceptThreshold score >= acceptThreshold is PASS
   * @param rejectThreshold score < rejectThreshold is REJECT; must be below the accept threshold
   */
  public EmbeddingRelevanceScorer(
      float[] onTopic, float[] offTopic, double acceptThreshold, double rejectThreshold) {
    validate(onTopic, offTopic, acceptThreshold, rejectThreshold);
    this.onTopic = onTopic;
    this.offTopic = offTopic;
    this.acceptThreshold = acceptThreshold;
    this.rejectThreshold = rejectThreshold;
  }

  @Override
  public RelevanceScore score(float[] embedding) {
    if (embedding == null || embedding.length != onTopic.length) {
      throw new IllegalArgumentException(
          "embedding length "
              + (embedding == null ? "null" : embedding.length)
              + " does not match centroid dimensions "
              + onTopic.length);
    }
    double cosineOn = cosine(embedding, onTopic);
    double cosineOff = cosine(embedding, offTopic);
    double score = Math.max(0, Math.min(1, (cosineOn - cosineOff + 1) / 2));
    RelevanceScore.Band band =
        score >= acceptThreshold
            ? RelevanceScore.Band.PASS
            : score < rejectThreshold ? RelevanceScore.Band.REJECT : RelevanceScore.Band.REVIEW;
    return new RelevanceScore(score, band);
  }

  /**
   * Standard cosine similarity between two equal-length vectors; 0 when either vector is
   * zero-length in magnitude.
   */
  public static double cosine(float[] a, float[] b) {
    if (a.length != b.length) {
      throw new IllegalArgumentException("vectors must have equal length");
    }
    double dot = 0;
    double normA = 0;
    double normB = 0;
    for (int i = 0; i < a.length; i++) {
      dot += (double) a[i] * b[i];
      normA += (double) a[i] * a[i];
      normB += (double) b[i] * b[i];
    }
    if (normA == 0 || normB == 0) {
      return 0;
    }
    return dot / (Math.sqrt(normA) * Math.sqrt(normB));
  }

  /**
   * The committed centroid pair loaded from {@link #CENTROIDS_RESOURCE}.
   *
   * @param dimensions embedding dimensionality both vectors must have
   * @param onTopic normalized on-topic centroid
   * @param offTopic normalized off-topic centroid
   */
  public record Centroids(int dimensions, float[] onTopic, float[] offTopic) {}

  /** Loads and validates the committed centroids JSON from the classpath. */
  public static Centroids loadCentroids() {
    try (InputStream in = EmbeddingRelevanceScorer.class.getResourceAsStream(CENTROIDS_RESOURCE)) {
      if (in == null) {
        throw new IllegalStateException("Missing filter centroids: " + CENTROIDS_RESOURCE);
      }
      Centroids centroids = new ObjectMapper().readValue(in, Centroids.class);
      if (centroids.dimensions() <= 0
          || centroids.onTopic() == null
          || centroids.offTopic() == null
          || centroids.onTopic().length != centroids.dimensions()
          || centroids.offTopic().length != centroids.dimensions()) {
        throw new IllegalStateException("Invalid filter centroids: " + CENTROIDS_RESOURCE);
      }
      return centroids;
    } catch (IOException e) {
      throw new IllegalStateException("Unreadable filter centroids: " + CENTROIDS_RESOURCE, e);
    }
  }

  private static void validate(
      float[] onTopic, float[] offTopic, double acceptThreshold, double rejectThreshold) {
    if (onTopic == null
        || offTopic == null
        || onTopic.length == 0
        || onTopic.length != offTopic.length) {
      throw new IllegalStateException("centroids must be non-empty and of equal length");
    }
    if (!(rejectThreshold >= 0 && acceptThreshold <= 1 && rejectThreshold < acceptThreshold)) {
      throw new IllegalStateException(
          "thresholds must satisfy 0 <= reject < accept <= 1, got reject="
              + rejectThreshold
              + " accept="
              + acceptThreshold);
    }
  }
}
